name: lobby
services:
  web:
    image: "node:20-bullseye"
    user: "node"
    working_dir: /usr/src
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/
    links:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: "yarn start"
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ok
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
    volumes:
      - ./config/docker/db/init:/docker-entrypoint-initdb.d
