name: lobby
services:
  web:
    container_name: web
    user: "node"
    working_dir: /usr/src
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    links:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: sh -c "yarn install && yarn start:dev "
  db:
    container_name: db
    image: mariadb
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ok
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
    volumes:
      - ./config/docker/db/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
